import { StyleSheet } from "react-native";
import { palette as c } from "@/constants/palette";

export const quizStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: c.background },
  content: {
    padding: 22,
    gap: 18,
    width: "100%",
    maxWidth: 580,
    alignSelf: "center",
    paddingBottom: 32,
  },
  loading: {
    padding: 28,
    gap: 24,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  header: { flexDirection: "row", alignItems: "center", gap: 12 },
  headerText: { flex: 1, gap: 5 },
  close: {
    minHeight: 44,
    minWidth: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  overline: {
    color: c.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.3,
  },
  topic: { color: c.ink, fontSize: 17, fontWeight: "700" },
  counter: {
    flexDirection: "row",
    gap: 6,
    padding: 10,
    borderRadius: 12,
    backgroundColor: c.soft,
  },
  link: { color: c.green, fontWeight: "700" },
  track: {
    height: 6,
    backgroundColor: c.line,
    borderRadius: 3,
    overflow: "hidden",
  },
  fill: { height: "100%", backgroundColor: c.green },
  row: { flexDirection: "row", justifyContent: "space-between", gap: 10 },
  body: { fontSize: 14, lineHeight: 22, color: c.muted },
  small: { fontSize: 12, lineHeight: 19, color: c.muted, flexShrink: 1 },
  card: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 26,
    padding: 26,
    alignItems: "center",
    gap: 17,
  },
  icon: { backgroundColor: c.soft, padding: 13, borderRadius: 18 },
  word: {
    fontSize: 38,
    fontWeight: "800",
    letterSpacing: -1,
    color: c.ink,
    textAlign: "center",
  },
  phonetic: { fontSize: 16, color: c.muted },
  title: { fontSize: 25, color: c.ink, fontWeight: "700", textAlign: "center" },
  prompt: { color: c.ink, fontWeight: "600", fontSize: 15 },
  answers: { gap: 10 },
  option: {
    minHeight: 62,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 16,
  },
  letter: {
    height: 34,
    width: 34,
    backgroundColor: c.soft,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: { color: c.ink, fontSize: 16, flex: 1, lineHeight: 23 },
  right: { borderColor: c.green, backgroundColor: "#EDF6EB" },
  wrong: { borderColor: c.danger, backgroundColor: "#FCECE8" },
  feedback: { padding: 18, borderRadius: 18, backgroundColor: c.soft, gap: 10 },
  feedbackWrong: { backgroundColor: "#FAEDE5" },
  feedbackTitle: { fontSize: 17, color: c.green, fontWeight: "700" },
  error: { color: c.danger },
  button: {
    minHeight: 50,
    padding: 16,
    backgroundColor: c.green,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  white: { color: "white", fontSize: 15, fontWeight: "700" },
  tip: { flexDirection: "row", padding: 12, gap: 9 },
  footer: { textAlign: "center", fontSize: 11, color: c.muted },
  stats: { gap: 8, alignItems: "center" },
  favorite: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  retryAnswer: {
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
  },
});
